name: CI - Empacar aplicacion

on:
  workflow_run:
    workflows: ["CI - Ejecutar pruebas"]
    types:
      - completed 

jobs:
  package:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install
        run: npm install

      - name: Empaquetado
        run: |
          mkdir -p package
          cp -r src/* package/
          cp package.json package/
          zip -r package.zip package/

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package.zip
