name: CI - Ejecutar pruebas

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Dependencias
        run: npm install

      - name: Tests
        run: npm test

      
